build:
	docker-compose -f users.yaml build
	docker-compose -f projects.yaml build

up:
	docker-compose -f users.yaml up -d
	docker-compose -f projects.yaml up -d

start:
	docker-compose -f users.yaml start
	docker-compose -f projects.yaml start

down:
	docker-compose -f users.yaml down
	docker-compose -f projects.yaml down

stop:
	docker-compose -f users.yaml stop
	docker-compose -f projects.yaml stop
